### ISSUE TITLE
Ferme - Impillable

### ISSUE THREAD

**Issue by Acenox** [ServeurHydeos/NeoliaMC#4]
**Donnez-nous les détails de votre bug**
On ne peut pas piller une ferme au creeper.

**Comment by ZwDck** [comment]
Bonjour,
J'écris ce post dans l'espoir de me faire remboursé 4 torches lvl 10 piller chez LaGarde. Certes mes preuves sont minces puisque je ne m'amuse pas à reccord mon gameplay, et vu que je ne suis pas youtuber donc un tel logiciel sur mon pc n'aurait que peu d'utilité. Mais je ne viendrai pas vous voir si je n'aurait pas réellement casser ses torches dans l'espoir qu'elle drop car je pensais le bug corrigé, j'ai donc seulement des screens des endroits où j'ai piller.
https://cdn.discordapp.com/attachments/631470464471924757/634054433323352084/unknown.png
https://cdn.discordapp.com/attachments/631470464471924757/634048547263610920/unknown.png
https://cdn.discordapp.com/attachments/631470464471924757/634054790296633391/unknown.png
https://cdn.discordapp.com/attachments/631470464471924757/634054605294010374/unknown.png
Je sais que j'ai peu de preuves mais je demande pas grands chose comparé à ce pillage : 
https://media.discordapp.net/attachments/529092057881640962/629294763484381200/unknown.png?width=974&height=553 
https://media.discordapp.net/attachments/628651588617109514/634056931891347457/unknown.png?width=1089&height=553
Où la les preuves ne font aucuns doutes. Je ne m'amuserai pas à faire une demande si je n'avais pas réellement casser les torches. 
ZwDck_

**Comment by Acenox** [comment]
Update : Je viens de corriger le bug de sauvegarde avec les anciennes fermes afin de ne pas perdre les données, néanmoins, il reste encore plusieurs bugs, donc j'ai peur que ça soit encore retardé de quelques jours.

**Comment by Acenox** [comment]
Update : Il reste un bug d'incompatibilité, j'attends la réponse du développeur pour pouvoir enfin déployer la mise à jour.
