### ISSUE TITLE
Clé de quest non drop

### ISSUE THREAD

**Issue by Sentoshi** [ServeurHydeos/NeoliaMC#61]
La quest de canne à sucre lvl2 ne drop pas de clé quand elle se termine

Pour le reproduire c'est simple, faut faire /quest puis aller dans les quest de farm puis sélectionner la quest de canne a sucre lvl2 

Désoler mais je n'ai pas de screen ou de vidéo :/

**Comment by Acenox** [comment]
Merci du signalement :) !

**Comment by Acenox** [comment]
Corrigé !
